### ISSUE TITLE
Why you use dig command?

### ISSUE THREAD

**Issue by jrichardsz** [whitecodel/ashani-admin#1]
I got this error:

```
Error: Command failed: dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 9,
  signal: null,
  cmd: 'dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com',
  stdout: ';; connection timed out; no servers could be reached\n',
  stderr: ''
}
```

Why are you using a network command on a simple express & ejs web?

**Comment by whitecodel** [comment]
**Thank you,
Richard Osmar Leon Ingaruca(@jrichardsz) for your feedback**
Actually, I have used these few network commands to show the information of the system but these commands are currently available for Linux, soon they will be used on other operating systems, till then I am leaving this issue open. When this issue is resolved, then I will close this issue.
